### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by yuanzhian** [webkixi/aotoo#1]
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

**Comment by webkixi** [comment]
应该是你的编译环境没有支持babel7
